-- Parcels table schema
-- Stores property parcel data with geospatial information
-- This table is typically populated from external parcel data sources

CREATE TABLE IF NOT EXISTS parcels (
    geoid                        TEXT,
    parcelnumb                   TEXT,
    parcelnumb_no_formatting     TEXT,
    state_parcelnumb             TEXT,
    account_number               TEXT,
    tax_id                       TEXT,
    alt_parcelnumb1              TEXT,
    alt_parcelnumb2              TEXT,
    alt_parcelnumb3              TEXT,
    usecode                      TEXT,
    usedesc                      TEXT,
    zoning                       TEXT,
    zoning_description           TEXT,
    struct                       TEXT,
    structno                     TEXT,
    yearbuilt                    INTEGER,
    year_built_effective_date    TEXT,
    numstories                   NUMERIC,
    numunits                     INTEGER,
    numrooms                     INTEGER,
    num_bath                     NUMERIC,
    num_bath_partial             NUMERIC,
    num_bedrooms                 INTEGER,
    structstyle                  TEXT,
    parvaltype                   TEXT,
    improvval                    NUMERIC,
    landval                      NUMERIC,
    parval                       NUMERIC,
    agval                        NUMERIC,
    saleprice                    NUMERIC,
    saledate                     TEXT,
    taxamt                       NUMERIC,
    taxyear                      INTEGER,
    last_ownership_transfer_date TEXT,
    owntype                      TEXT,
    owner                        TEXT,
    unmodified_owner             TEXT,
    ownfrst                      TEXT,
    ownlast                      TEXT,
    owner2                       TEXT,
    owner3                       TEXT,
    owner4                       TEXT,
    previous_owner               TEXT,
    mailadd                      TEXT,
    mail_address2                TEXT,
    careof                       TEXT,
    mail_addno                   TEXT,
    mail_addpref                 TEXT,
    mail_addstr                  TEXT,
    mail_addsttyp                TEXT,
    mail_addstsuf                TEXT,
    mail_unit                    TEXT,
    mail_city                    TEXT,
    mail_state2                  TEXT,
    mail_zip                      TEXT,
    mail_country                 TEXT,
    mail_urbanization             TEXT,
    original_mailing_address     TEXT,
    address                      TEXT,
    address2                     TEXT,
    saddno                       TEXT,
    saddpref                     TEXT,
    saddstr                      TEXT,
    saddsttyp                    TEXT,
    saddstsuf                    TEXT,
    sunit                        TEXT,
    scity                        TEXT,
    original_address             TEXT,
    city                         TEXT,
    county                       TEXT,
    state2                       TEXT,
    szip                         TEXT,
    szip5                        TEXT,
    urbanization                 TEXT,
    location_name                TEXT,
    address_source               TEXT,
    legaldesc                    TEXT,
    plat                         TEXT,
    book                         TEXT,
    page                         TEXT,
    block                        TEXT,
    lot                          TEXT,
    neighborhood                 TEXT,
    neighborhood_code            TEXT,
    subdivision                  TEXT,
    lat                          DOUBLE PRECISION,
    lon                          DOUBLE PRECISION,
    qoz                          BOOLEAN,
    qoz_tract                    TEXT,
    census_tract                 TEXT,
    census_block                 TEXT,
    census_blockgroup            TEXT,
    census_zcta                  TEXT,
    ll_last_refresh              TEXT,
    sourceurl                    TEXT,
    recrdareatx                  TEXT,
    recrdareano                  NUMERIC,
    area_building                NUMERIC,
    area_building_definition     TEXT,
    deeded_acres                 NUMERIC,
    gisacre                      NUMERIC,
    sqft                         NUMERIC,
    ll_gisacre                   NUMERIC,
    ll_gissqft                   NUMERIC,
    plss_township                TEXT,
    plss_section                 TEXT,
    plss_range                   TEXT,
    reviseddate                  TEXT,
    path                         TEXT,
    ll_stable_id                 TEXT,
    ll_uuid                      UUID,
    ll_stack_uuid                UUID,
    ll_updated_at                TIMESTAMP WITH TIME ZONE,
    kspid                        TEXT,
    co_abbr                      TEXT,
    dateparcels                  TEXT,
    mailing_address              TEXT,
    boundary_desc                TEXT,
    property_status               TEXT,
    taxing_unit                  TEXT,
    geom                         geometry(Point, 4326),
    id                           BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    s_t_r                        TEXT,
    quickrefid                   TEXT,
    situsaddr                    TEXT,
    ownername                    TEXT,
    owneraddr                    TEXT,
    cic_tax                      TEXT,
    prc_2024                     TEXT,
    prc_2025                     TEXT,
    parcel_id                    TEXT,
    propertynumber               TEXT,
    pid_app                      TEXT,
    pid_tax                      TEXT,
    taxingunitcode               TEXT,
    taxingunitdesc               TEXT,
    neighborhooddesc             TEXT,
    residualland                 NUMERIC,
    totalagacres                 NUMERIC,
    totalagacresdr               NUMERIC,
    totalagvaluedr               NUMERIC,
    totalagacresir               NUMERIC,
    totalagvalueir               NUMERIC,
    totalagacresng               NUMERIC,
    totalagvalueng               NUMERIC,
    totalagacrestg               NUMERIC,
    totalagvaluetg               NUMERIC,
    totalacres                   NUMERIC,
    township                     TEXT,
    section_                     TEXT,
    subdivisionnumber            TEXT,
    addresscomplete              TEXT,
    addressnumber                TEXT,
    addresscity                  TEXT,
    point_x                      DOUBLE PRECISION,
    point_y                      DOUBLE PRECISION,
    
    CONSTRAINT parcels_pkey PRIMARY KEY (id)
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS parcels_county_state_ix ON parcels USING btree (state2, county);
CREATE INDEX IF NOT EXISTS parcels_geoid_ix ON parcels USING btree (geoid);
CREATE INDEX IF NOT EXISTS parcels_geom_gix ON parcels USING gist (geom);
CREATE INDEX IF NOT EXISTS parcels_parcelnumb_ix ON parcels USING btree (parcelnumb);
CREATE UNIQUE INDEX IF NOT EXISTS parcels_parcelnumb_uidx ON parcels USING btree (parcelnumb);

-- Grant permissions
GRANT SELECT, INSERT, UPDATE, DELETE ON parcels TO agadmin;
GRANT USAGE, SELECT ON SEQUENCE parcels_id_seq TO agadmin;

-- Add comment
COMMENT ON TABLE parcels IS 'Property parcel data with geospatial information for mapping and analysis';

