-- Views for parcel analysis and facility-customer relationships
-- These views support analysis of parcels within 8 miles of facilities

-- View: beaver_8_mile
-- Shows all parcels within 8 miles of the Beaver Grain Corp facility (parcel ID 10746)
CREATE OR REPLACE VIEW beaver_8_mile AS
SELECT 
    row_number() OVER () AS gid,
    p.geoid,
    p.parcelnumb,
    p.parcelnumb_no_formatting,
    p.state_parcelnumb,
    p.account_number,
    p.tax_id,
    p.alt_parcelnumb1,
    p.alt_parcelnumb2,
    p.alt_parcelnumb3,
    p.usecode,
    p.usedesc,
    p.zoning,
    p.zoning_description,
    p.struct,
    p.structno,
    p.yearbuilt,
    p.year_built_effective_date,
    p.numstories,
    p.numunits,
    p.numrooms,
    p.num_bath,
    p.num_bath_partial,
    p.num_bedrooms,
    p.structstyle,
    p.parvaltype,
    p.improvval,
    p.landval,
    p.parval,
    p.agval,
    p.saleprice,
    p.saledate,
    p.taxamt,
    p.taxyear,
    p.last_ownership_transfer_date,
    p.owntype,
    p.owner,
    p.unmodified_owner,
    p.ownfrst,
    p.ownlast,
    p.owner2,
    p.owner3,
    p.owner4,
    p.previous_owner,
    p.mailadd,
    p.mail_address2,
    p.careof,
    p.mail_addno,
    p.mail_addpref,
    p.mail_addstr,
    p.mail_addsttyp,
    p.mail_addstsuf,
    p.mail_unit,
    p.mail_city,
    p.mail_state2,
    p.mail_zip,
    p.mail_country,
    p.mail_urbanization,
    p.original_mailing_address,
    p.address,
    p.address2,
    p.saddno,
    p.saddpref,
    p.saddstr,
    p.saddsttyp,
    p.saddstsuf,
    p.sunit,
    p.scity,
    p.original_address,
    p.city,
    p.county,
    p.state2,
    p.szip,
    p.szip5,
    p.urbanization,
    p.location_name,
    p.address_source,
    p.legaldesc,
    p.plat,
    p.book,
    p.page,
    p.block,
    p.lot,
    p.neighborhood,
    p.neighborhood_code,
    p.subdivision,
    p.lat,
    p.lon,
    p.qoz,
    p.qoz_tract,
    p.census_tract,
    p.census_block,
    p.census_blockgroup,
    p.census_zcta,
    p.ll_last_refresh,
    p.sourceurl,
    p.recrdareatx,
    p.recrdareano,
    p.area_building,
    p.area_building_definition,
    p.deeded_acres,
    p.gisacre,
    p.sqft,
    p.ll_gisacre,
    p.ll_gissqft,
    p.plss_township,
    p.plss_section,
    p.plss_range,
    p.reviseddate,
    p.path,
    p.ll_stable_id,
    p.ll_uuid,
    p.ll_stack_uuid,
    p.ll_updated_at,
    p.kspid,
    p.co_abbr,
    p.dateparcels,
    p.mailing_address,
    p.boundary_desc,
    p.property_status,
    p.taxing_unit,
    p.geom,
    p.id
FROM parcels p
JOIN parcels c ON c.id = 10746  -- Beaver Grain Corp facility
WHERE p.geom IS NOT NULL 
  AND c.geom IS NOT NULL 
  AND ST_DWithin(
      p.geom::geography, 
      c.geom::geography, 
      (8::numeric * 1609.344)::double precision
  );

-- Grant permissions
GRANT SELECT ON beaver_8_mile TO agadmin;

-- Add comment
COMMENT ON VIEW beaver_8_mile IS 'All parcels within 8 miles of Beaver Grain Corp facility (parcel ID 10746)';

-- View: beaver_8_mile_ag
-- Shows agricultural parcels within 8 miles of the Beaver Grain Corp facility
CREATE OR REPLACE VIEW beaver_8_mile_ag AS
SELECT 
    row_number() OVER () AS gid,
    p.geoid,
    p.parcelnumb,
    p.parcelnumb_no_formatting,
    p.state_parcelnumb,
    p.account_number,
    p.tax_id,
    p.alt_parcelnumb1,
    p.alt_parcelnumb2,
    p.alt_parcelnumb3,
    p.usecode,
    p.usedesc,
    p.zoning,
    p.zoning_description,
    p.struct,
    p.structno,
    p.yearbuilt,
    p.year_built_effective_date,
    p.numstories,
    p.numunits,
    p.numrooms,
    p.num_bath,
    p.num_bath_partial,
    p.num_bedrooms,
    p.structstyle,
    p.parvaltype,
    p.improvval,
    p.landval,
    p.parval,
    p.agval,
    p.saleprice,
    p.saledate,
    p.taxamt,
    p.taxyear,
    p.last_ownership_transfer_date,
    p.owntype,
    p.owner,
    p.unmodified_owner,
    p.ownfrst,
    p.ownlast,
    p.owner2,
    p.owner3,
    p.owner4,
    p.previous_owner,
    p.mailadd,
    p.mail_address2,
    p.careof,
    p.mail_addno,
    p.mail_addpref,
    p.mail_addstr,
    p.mail_addsttyp,
    p.mail_addstsuf,
    p.mail_unit,
    p.mail_city,
    p.mail_state2,
    p.mail_zip,
    p.mail_country,
    p.mail_urbanization,
    p.original_mailing_address,
    p.address,
    p.address2,
    p.saddno,
    p.saddpref,
    p.saddstr,
    p.saddsttyp,
    p.saddstsuf,
    p.sunit,
    p.scity,
    p.original_address,
    p.city,
    p.county,
    p.state2,
    p.szip,
    p.szip5,
    p.urbanization,
    p.location_name,
    p.address_source,
    p.legaldesc,
    p.plat,
    p.book,
    p.page,
    p.block,
    p.lot,
    p.neighborhood,
    p.neighborhood_code,
    p.subdivision,
    p.lat,
    p.lon,
    p.qoz,
    p.qoz_tract,
    p.census_tract,
    p.census_block,
    p.census_blockgroup,
    p.census_zcta,
    p.ll_last_refresh,
    p.sourceurl,
    p.recrdareatx,
    p.recrdareano,
    p.area_building,
    p.area_building_definition,
    p.deeded_acres,
    p.gisacre,
    p.sqft,
    p.ll_gisacre,
    p.ll_gissqft,
    p.plss_township,
    p.plss_section,
    p.plss_range,
    p.reviseddate,
    p.path,
    p.ll_stable_id,
    p.ll_uuid,
    p.ll_stack_uuid,
    p.ll_updated_at,
    p.kspid,
    p.co_abbr,
    p.dateparcels,
    p.mailing_address,
    p.boundary_desc,
    p.property_status,
    p.taxing_unit,
    p.geom,
    p.id,
    ST_Distance(p.geom::geography, c.geom::geography) / 1609.344::double precision AS distance_miles
FROM parcels p
JOIN parcels c ON c.id = 10746  -- Beaver Grain Corp facility
WHERE p.geom IS NOT NULL 
  AND c.geom IS NOT NULL 
  AND (p.usedesc = 'Agricultural Use' OR p.usedesc = 'Farm Homesite')
  AND ST_DWithin(
      p.geom::geography, 
      c.geom::geography, 
      (8::numeric * 1609.344)::double precision
  );

-- Grant permissions
GRANT SELECT ON beaver_8_mile_ag TO agadmin;

-- Add comment
COMMENT ON VIEW beaver_8_mile_ag IS 'Agricultural parcels within 8 miles of Beaver Grain Corp facility with distance calculation';

-- View: facility_parcels_8mi
-- Shows all parcels within 8 miles of active grain elevator facilities (United Ag Services)
CREATE OR REPLACE VIEW facility_parcels_8mi AS
SELECT 
    row_number() OVER () AS gid,
    f.facility_id,
    f.name AS facility_name,
    f.company_id,
    f.facility_type_id,
    p.geoid,
    p.parcelnumb,
    p.parcelnumb_no_formatting,
    p.state_parcelnumb,
    p.account_number,
    p.tax_id,
    p.alt_parcelnumb1,
    p.alt_parcelnumb2,
    p.alt_parcelnumb3,
    p.usecode,
    p.usedesc,
    p.zoning,
    p.zoning_description,
    p.struct,
    p.structno,
    p.yearbuilt,
    p.year_built_effective_date,
    p.numstories,
    p.numunits,
    p.numrooms,
    p.num_bath,
    p.num_bath_partial,
    p.num_bedrooms,
    p.structstyle,
    p.parvaltype,
    p.improvval,
    p.landval,
    p.parval,
    p.agval,
    p.saleprice,
    p.saledate,
    p.taxamt,
    p.taxyear,
    p.last_ownership_transfer_date,
    p.owntype,
    p.owner,
    p.unmodified_owner,
    p.ownfrst,
    p.ownlast,
    p.owner2,
    p.owner3,
    p.owner4,
    p.previous_owner,
    p.mailadd,
    p.mail_address2,
    p.careof,
    p.mail_addno,
    p.mail_addpref,
    p.mail_addstr,
    p.mail_addsttyp,
    p.mail_addstsuf,
    p.mail_unit,
    p.mail_city,
    p.mail_state2,
    p.mail_zip,
    p.mail_country,
    p.mail_urbanization,
    p.original_mailing_address,
    p.address,
    p.address2,
    p.saddno,
    p.saddpref,
    p.saddstr,
    p.saddsttyp,
    p.saddstsuf,
    p.sunit,
    p.scity,
    p.original_address,
    p.city,
    p.county,
    p.state2,
    p.szip,
    p.szip5,
    p.urbanization,
    p.location_name,
    p.address_source,
    p.legaldesc,
    p.plat,
    p.book,
    p.page,
    p.block,
    p.lot,
    p.neighborhood,
    p.neighborhood_code,
    p.subdivision,
    p.lat,
    p.lon,
    p.qoz,
    p.qoz_tract,
    p.census_tract,
    p.census_block,
    p.census_blockgroup,
    p.census_zcta,
    p.ll_last_refresh,
    p.sourceurl,
    p.recrdareatx,
    p.recrdareano,
    p.area_building,
    p.area_building_definition,
    p.deeded_acres,
    p.gisacre,
    p.sqft,
    p.ll_gisacre,
    p.ll_gissqft,
    p.plss_township,
    p.plss_section,
    p.plss_range,
    p.reviseddate,
    p.path,
    p.ll_stable_id,
    p.ll_uuid,
    p.ll_stack_uuid,
    p.ll_updated_at,
    p.kspid,
    p.co_abbr,
    p.dateparcels,
    p.mailing_address,
    p.boundary_desc,
    p.property_status,
    p.taxing_unit,
    p.geom,
    p.id,
    p.s_t_r,
    p.quickrefid,
    p.situsaddr,
    p.ownername,
    p.owneraddr,
    p.cic_tax,
    p.prc_2024,
    p.prc_2025,
    p.parcel_id,
    p.propertynumber,
    p.pid_app,
    p.pid_tax,
    p.taxingunitcode,
    p.taxingunitdesc,
    p.neighborhooddesc,
    p.residualland,
    p.totalagacres,
    p.totalagacresdr,
    p.totalagvaluedr,
    p.totalagacresir,
    p.totalagvalueir,
    p.totalagacresng,
    p.totalagvalueng,
    p.totalagacrestg,
    p.totalagvaluetg,
    p.totalacres,
    p.township,
    p.section_,
    p.subdivisionnumber,
    p.addresscomplete,
    p.addressnumber,
    p.addresscity,
    p.point_x,
    p.point_y,
    ST_Distance(p.geom::geography, f.geom::geography) / 1609.344::double precision AS distance_miles
FROM facility f
JOIN parcels p ON p.geom IS NOT NULL
WHERE f.company_id IN (1, 8)  -- United Ag Services companies
  AND f.facility_type_id = 1  -- Grain Elevator
  AND f.status = 'ACTIVE'
  AND f.geom IS NOT NULL
  AND ST_DWithin(
      p.geom::geography, 
      f.geom::geography, 
      (8::numeric * 1609.344)::double precision
  );

-- Grant permissions
GRANT SELECT ON facility_parcels_8mi TO agadmin;

-- Add comment
COMMENT ON VIEW facility_parcels_8mi IS 'All parcels within 8 miles of active grain elevator facilities (United Ag Services) with distance calculation';

-- View: facility_customers_8mi
-- Aggregates parcel owners within 8 miles of facilities (all use types)
CREATE OR REPLACE VIEW facility_customers_8mi AS
SELECT 
    facility_name,
    owner,
    MAX(mailadd) AS mailadd,
    MAX(mail_address2) AS mail_address2,
    MAX(mail_city) AS mail_city,
    MAX(mail_state2) AS mail_state2,
    MAX(mail_zip) AS mail_zip,
    SUM(COALESCE(ll_gisacre, 0::numeric)) AS total_ll_gisacre,
    COUNT(*) AS parcel_count
FROM facility_parcels_8mi v
WHERE owner IS NOT NULL 
  AND btrim(owner) <> ''
GROUP BY facility_name, owner;

-- Grant permissions
GRANT SELECT ON facility_customers_8mi TO agadmin;

-- Add comment
COMMENT ON VIEW facility_customers_8mi IS 'Aggregated customer list (parcel owners) within 8 miles of facilities, grouped by facility and owner';

-- View: facility_customers_8mi_ag
-- Aggregates agricultural parcel owners within 8 miles of facilities
CREATE OR REPLACE VIEW facility_customers_8mi_ag AS
SELECT 
    facility_id,
    facility_name,
    owner,
    MAX(mailadd) AS mailadd,
    MAX(mail_address2) AS mail_address2,
    MAX(mail_city) AS mail_city,
    MAX(mail_state2) AS mail_state2,
    MAX(mail_zip) AS mail_zip,
    SUM(COALESCE(ll_gisacre, 0::numeric)) AS total_ll_gisacre,
    COUNT(*) AS parcel_count
FROM facility_parcels_8mi v
WHERE owner IS NOT NULL 
  AND btrim(owner) <> ''
  AND usedesc IN ('Agricultural Use', 'Farm Homesite')
GROUP BY facility_id, facility_name, owner;

-- Grant permissions
GRANT SELECT ON facility_customers_8mi_ag TO agadmin;

-- Add comment
COMMENT ON VIEW facility_customers_8mi_ag IS 'Aggregated agricultural customer list (parcel owners) within 8 miles of facilities, grouped by facility and owner';

